import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import ToastProvider from '@/provider/ToastProvider'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ActiveBnb | Hosting',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ToastProvider />
        {children}
      </body>
    </html>
  )
}
